# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.11.0
_src_path: gl:openscm/copier-core-python-repository
conda_release: false
email: zebedee.nicholls@climate-energy-college.org
include_cli: false
name: Zebedee Nicholls
notebook_based_docs: true
package_manager: uv
pandas_doctests: true
plot_dependencies: true
project_description_short: Pandas accessors for OpenSCM-related functionality.
project_name_human: Pandas-OpenSCM
project_name_pip: pandas-openscm
project_name_python: pandas_openscm
project_url: https://github.com/openscm/pandas-openscm
track_lock_file: true
